# Generated by Django 3.0.1 on 2020-01-12 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='login_auth',
        ),
    ]
